media playlist
Artofpaganini/Media-play-list-Task3.2-Dobrov- pull request #1
Opened 2020-09-21 14:02 UTC by Artofpaganini

2020-09-22 10:03 UTC, Akvit requested changes

2020-09-22 10:03 UTC, Akvit commented on app/src/main/AndroidManifest.xml
> +<!--        <provider-->
- [x] комменты убери

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/db/DBHelper.java
> +    public DBHelper(@Nullable Context context) {
а как это контекст может быть у тебя нулёвым?

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/db/SongContract.java
> +    public SongContract() {
лишний код

- [x] убери

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/entities/Song.java
> +    public Song(String name, String artist, String styleOfMusic, String uriAddress) {
аннотации @nullable/@notnull

- [x] check

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/entities/SongListData.java
> +    public SongListData(Context context) {
ты зачем сюда передаёшь контекст? это может привести к утечку памяти
- [x] убери

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/MainActivity.java
> +        chooseTheArtist.setOnClickListener(new View.OnClickListener() {
- [x] лямбда

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/MainActivity.java
> +    public void openActivity() {
- [x] private

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/MyAdapter.java
> +    public MyAdapter(List<Song> songListFromDB) {
- [x] аннотация

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/MyAdapter.java
> +    //__________________________________________________________
- [x] убери линию

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/MyAdapter.java
> +
- [ ] создаёшь в холдере публичный метод bind, куда передаёшь модель song и разбираешь её на составляющие

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/MyAdapter.java
> +//        holder.uri_music_address.setText(song.getUriAddress());
- [x] коммент убери

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/MyAdapter.java
> +//            uri_music_address = itemView.findViewById(R.id.uri_music_address);
- [x] коммент убери

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +
- [x] сгруппируй код и вынеси его кусочками по приватным методам

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +//        chooseByStyle.setSelection(getIndexStyleByChoosenArtist(actualStyle));
- [x] коммент убери

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    public void adapterSpinner(Spinner spinner, List<String> songList) {
- [x] аннотация

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    public String getStyleAccordingArtist(List<Song> artist) {
почему паблик? Ты получаешь экземпляр активити где-то ещё?
- [x] аннотация + private

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    private void getSongsByChoosenItemByArtistFromSpinner(Spinner spinner) {
- [x] аннотация

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    private List<Song> getSongNameByChoosenArtist(String selectedArtist) {
- [x] аннотация

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    private List<Song> getSongNameByChoosenStyle(String selectedStyle) {
- [x] аннотация

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    private int getIndexStyleByChoosenArtist(String selectedStyle) {
- [x] аннтоция

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    private List<String> getArtistSpinner(List<Song> allSongsFromDb) {
- [x] аннтоция

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    private void addSongToDB(SQLiteDatabase database) {
- [ ] аннотация

2020-09-22 10:03 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/service/NewActivity.java
> +    public List<Song> getSongsFromDB(SQLiteDatabase database) {
- [ ] аннотация

2020-09-22 10:03 UTC, Akvit commented on app/src/main/res/layout/item_view.xml
> +<!--        android:textSize="@dimen/text_size_uri"-->
- [ ] коменты убери

2020-09-22 10:20 UTC, Artofpaganini commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/db/DBHelper.java
> +    public DBHelper(@Nullable Context context) {
Исправил!

2020-09-23 07:07 UTC, Akvit requested changes

2020-09-23 07:07 UTC, Akvit commented on app/src/main/java/by/andresen/intern/dobrov/contentprovider/entities/SongListData.java
> +        List<Song> songListForDb = new ArrayList<>();
- [ ] "android.resource://" лучше в константу. Ты передавал сюда контекст раньше для получения package name? мог бы сразу этот package name передавать в метод

2020-09-23 18:10 UTC, merged