simple Media Player
Artofpaganini/Media-play-list-Task3.2-Dobrov- pull request #2
Opened 2020-09-23 18:18 UTC by Artofpaganini

Connected  media player  and  playlist for media player,  from broadcast receiver

2020-09-23 20:15 UTC, Akvit requested changes

2020-09-23 20:15 UTC, Akvit commented on app3.1/src/main/java/by/andersen/intern/serviceplaymusicfile/activies/MainActivity.java
> +    private String songName;
- [x] вынеси эти стринги в объект и сразу мержи

2020-09-24 10:28 UTC, Artofpaganini commented
Строки перенесены в класс сонг, 
Исправлена ошибка  при запуске плей   перед  выбором исполнителя

2020-09-24 10:52 UTC, Akvit requested changes

2020-09-24 10:52 UTC, Akvit commented on app3.1/src/main/java/by/andersen/intern/serviceplaymusicfile/activies/MainActivity.java
> +        editor.putString("saveSongName", songData.getSongName());
- [ ] константы

2020-09-24 10:52 UTC, Akvit commented on app3.1/src/main/java/by/andersen/intern/serviceplaymusicfile/activies/MainActivity.java
> +        songData.setSongName(sharedPreferences.getString("saveSongName", null));
- [ ] константы

2020-09-24 10:52 UTC, Akvit commented on app3.1/src/main/java/by/andersen/intern/serviceplaymusicfile/activies/SongData.java
> +    public SongData() {
- [ ] лишний конструктор

2020-09-24 10:52 UTC, Akvit commented on app3.1/src/main/java/by/andersen/intern/serviceplaymusicfile/activies/SongData.java
> +    public void setSongName(String songName) {
- [ ] аннотация

2020-09-24 10:55 UTC, Akvit requested changes

2020-09-24 10:55 UTC, Akvit commented on app3.1/.gitignore
> +### AndroidStudio ###
- [ ] в settings.gradle

include ':app3.2'
include ':app3.1'

2020-09-24 11:16 UTC, merged